### ISSUE TITLE
Proposal to join forces

### ISSUE THREAD

**Issue by StarGate01** [LelouBil/AmongUsMumbleLink#2]
We are currently developing a mod very similar to yours: https://github.com/StarGate01/AmongUs-Mumble .

It uses a slightly different approach, instead of scanning the memory it hooks directly into the game using C++.

If you want to, you could join us and we would consolidate our efforts. If you want to continue your own version, that's perfectly fine too, more ways to achieve a goal is also beneficial.

**Comment by LelouBil** [comment]
Thanks, I just joined the discord. I'm not really good at c++ but I'll try to help :)
